alias otr := open-tests-results  
alias t := test

open-tests-results:
    open demo/build/reports/androidTests/connected/com.hypertrack.sdk.webview.android.demo.MainActivityTest.html

release:
    echo "Success"

release-to-maven:
    ./gradlew releaseToS3

test:
    just -f ../js/justfile ca
    ./gradlew demo:connectedDebugAndroidTest --info | grep "> test\["
    cat demo/build/reports/androidTests/connected/com.hypertrack.sdk.webview.android.demo.MainActivityTest.html | grep "<pre>" || true
