alias b := build
alias u := update-local-wrapper

build:
    just -f ../js-library/justfile build
    just update-local-wrapper
    bun build src/index.ts --outdir dist

update-local-wrapper:
    bun remove hypertrack-sdk-webview
    bun add ../js-library
