alias ag := add-from-github
alias al := update-local-wrapper
alias b := build
alias u := update-local-wrapper

add-from-github version="no-data":
    bun remove hypertrack-sdk-webview
    bun add git+https://github.com/hypertrack/sdk-webview.git#{{version}}

build:
    just -f ../js-library/justfile build
    just update-local-wrapper
    bun build src/index.ts --outdir dist

update-local-wrapper:
    bun remove hypertrack-sdk-webview
    bun add ../js-library
